# title: "Sam Foreman"
# date: last-modified
google-scholar: true
metadata-files:
  - quarto/_website.yml
  - quarto/_format.yml
lightbox: true
# filters:
#   - collapse-social-embeds
# date: today
# author-title: ""
# affiliation-title: ""
# location-title: ""
# published-title: ""
# modified-title: ""
date-modified: last-modified
title-block-categories: true
number-sections: false
image-lazy-loading: true
bibliography: references.bib
# appendix-cite-as: display
# favicon: "assets/sf.png"
# twitter-card: true
site-url: "https://samforeman.me"
# citeproc: true
brand: _brand.yml
# brand:
#   light: light-brand.yml
#   dark: dark-brand.yml
project:
  type: website
  output-dir: docs
  execute-dir: project
  # post-render:
  #   - post-render.py
  # #   - post-render.ts
  preview:
    port: 4209
  render:
    - "index.qmd"
    - "./about/index.qmd"
    - "./now/index.qmd"
    - "./ideas/index.qmd"
    - "./posts/**/*.qmd"
    - "./slides/**/*.qmd"
    - "./talks/**/*.qmd"
    # - "!./talks/2025/09/24/index.qmd"
    # - "!./talks/2025/10/15/index.qmd"
    - "./more/**/*.qmd"
    - "./projects/index.qmd"
    - "!posts/test/l2hmc-4dSU3-execute/index.qmd"
    - "!./posts/test/**"
    - "!./posts/jupyter/l2hmc-test/index.qmd"
    - "!../talks/**test**"
    - "!talks/test/index.qmd"
    - "!*old*"
    - "!/drafts/"
  resources:
    - ./static/icons/github-loop.svg
    - ./static/icons/sunny-outline.svg
    - ./static/icons/moon-outline-loop.svg
    - ./static/icons/sun-cloud.svg
    - ./static/icons/moon-cloud.svg
    - ./static/files/resume.pdf
    - ./static/files/oneapi-talk/
    - ./static/files/superconductivity.pdf
    - ./static/fonts/MIosevkaQp/WOFF2/MIosevkaQp-Regular.woff2
    - ./static/fonts/MIosevkaQp/WOFF2/MIosevkaQp-Italic.woff2
    - ./static/fonts/MIosevkaQp/WOFF2/MIosevkaQp-Bold.woff2
    - ./static/fonts/MIosevkaQp/WOFF2/MIosevkaQp-BoldItalic.woff2
    - ./static/fonts/MIosevkaQp/WOFF2/MIosevkaQp-SemiCondensed.woff2
    - ./static/fonts/MIosevkaQp/WOFF2/MIosevkaQp-SemiCondensedBold.woff2
    - ./static/fonts/MIosevkaQp/MIosevkaQp.css
    - ./static/fonts/MIosevkaTerm/WOFF2/MIosevkaTerm-Regular.woff2
    - ./static/fonts/MIosevkaTerm/WOFF2/MIosevkaTerm-Italic.woff2
    - ./static/fonts/MIosevkaTerm/WOFF2/MIosevkaTerm-Bold.woff2
    - ./static/fonts/MIosevkaTerm/WOFF2/MIosevkaTerm-BoldItalic.woff2
    - ./static/fonts/MIosevkaTerm/MIosevkaTerm.css
    - ./css/ibm-plex.css
affiliation: "[Argonne  National Laboratory](https://alcf.anl.gov/about/people/sam-foreman)"
author:
  name: "Sam Foreman"
  url: "https://samforeman.me"
  email: "foremans@anl.gov"
  orcid: 0000-0002-9981-0876
  affiliation: "[ALCF](https://alcf.anl.gov/about/people/sam-foreman)"
  affiliation-url: "https://alcf.anl.gov/about/people/sam-foreman"
# orcid: 0000-0002-9981-0876
citation: true
# citation:
#   author: Sam Foreman
#   type: webpage
#   url: https://samforeman.me
execute:
  cache: true
  freeze: auto
