# title: "Sam Foreman"
# date: last-modified
google-scholar: true
metadata-files:
  - quarto/_website.yml
  - quarto/_format.yml
lightbox: true
# filters:
#   - collapse-social-embeds
# date: today
# author-title: ""
# affiliation-title: ""
# location-title: ""
# published-title: ""
# modified-title: ""
date-modified: last-modified
title-block-categories: true
number-sections: false
image-lazy-loading: true
bibliography: references.bib
# appendix-cite-as: display
# favicon: "assets/sf.png"
# twitter-card: true
site-url: "https://samforeman.me"
# citeproc: true
project:
  type: website
  output-dir: docs
  execute-dir: project
  # post-render:
  #   - post-render.py
  # #   - post-render.ts
  preview:
    port: 4209
  render:
    - "index.qmd"
    - "./about/index.qmd"
    - "./now/index.qmd"
    - "./ideas/index.qmd"
    - "./posts/**/*.qmd"
    - "./slides/**/*.qmd"
    - "./talks/**/*.qmd"
    - "./more/**/*.qmd"
    - "./projects/index.qmd"
    - "!posts/test/l2hmc-4dSU3-execute/index.qmd"
    - "!./posts/test/**"
    - "!./posts/jupyter/l2hmc-test/index.qmd"
    - "!../talks/**test**"
    - "!talks/test/index.qmd"
    - "!*old*"
    - "!/drafts/"
    # - "./projects/**/*.qmd"
    # - "!./talks/test/index.qmd"
    # - "./projects/hpc-bootcamp-2025/index.qmd"
    # # - "./projects/hpc-bootcamp-2025/00-intro-supercomputers/**/**/*.qmd"
    # - "./projects/hpc-bootcamp-2025/00-intro-AI-HPC/**/**/*.qmd"
    # - "./projects/hpc-bootcamp-2025/01-neural-networks/**/**/*.qmd"
    # - "./projects/hpc-bootcamp-2025/02-llms/index.qmd"
    # - "./projects/hpc-bootcamp-2025/02-llms/0-intro-to-llms/index.qmd"
    # - "./projects/hpc-bootcamp-2025/02-llms/0-intro-to-llms/index.qmd"
    #
    # - "./projects/hpc-bootcamp-2025/03-ai-for-science/index.qmd"
    # - "projects/climate-analysis/**/*.qmd"
    # - "./projects/climate-analysis/000-Overview/*.qmd"
    # - "./projects/climate-analysis/001-GettingStarted/*.qmd"
    # - "./projects/climate-analysis/001-GettingStarted/chicago-temp.qmd"
    # - "./projects/climate-analysis/extras/*.qmd"
    # - "./posts/**/index.ipynb"
    # - "posts/ai-for-physics/l2hmc-qcd/4dSU3nb/index.qmd"
    # - "./posts/ai-for-physics/l2hmc-qcd/4dSU3nb/index.qmd"
    # - "!./posts/ai-for-physics/l2hmc-qcd/4dSU3/index.qmd"
    # - "!posts/ai-for-physics/l2hmc-qcd/4dSU3/index.qmd"
    # - "!posts/ai-for-physics/l2hmc-qcd/4dSU3-alt/index.qmd"
    # - "!posts/ai-for-physics/l2hmc-qcd/4dSU3-2025-04-04-092808/index.qmd"
    # - "!./posts/ai-for-physics/l2hmc-qcd/4dSU3/index.qmd"
    # - "./qmd/**/*.qmd"
    # - "https://github.com/saforem2/l2hmc-qcd/blob/main/qmd/diffusion/diffusion.qmd"
  # resources:
  #   - ./static/files/resume.pdf
  #   - ./static/files/superconductivity.pdf
  #   - ./static/files/oneapi-talk/
  resources:
    - ./static/files/resume.pdf
    - ./static/files/superconductivity.pdf
    - ./static/files/oneapi-talk/
    - ./static/fonts/MIosevkaQp/**/*.woff2
    - ./static/fonts/MIosevkaQp/**/*.ttf
    - ./static/fonts/MIosevkaQp/MIosevkaQp.css
    - ./static/fonts/MIosevkaTerm/**/*.woff2
    - ./static/fonts/MIosevkaTerm/**/*.ttf
    - ./static/fonts/MIosevkaTerm/MIosevkaTerm.css
    - ./css/ibm-plex.css
# author:
#   name: "[Sam Foreman]{.dim-text} [[{{< ai orcid >}}]{.orcid-green}](https://orcid.org/0000-0002-9981-0876)"
#   url: https://samforeman.me
#   email: foremans@anl.gov
#   # affiliation: \[ALCF\]
#   # affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
affiliation: "[Argonne  National Laboratory](https://alcf.anl.gov/about/people/sam-foreman)"
author:
  name: "Sam Foreman"
  url: "https://samforeman.me"
  email: "foremans@anl.gov"
  orcid: 0000-0002-9981-0876
  affiliation: "[ALCF](https://alcf.anl.gov/about/people/sam-foreman)"
  affiliation-url: "https://alcf.anl.gov/about/people/sam-foreman"
# orcid: 0000-0002-9981-0876
citation: true
# citation:
#   author: Sam Foreman
#   type: webpage
#   url: https://samforeman.me
execute:
  cache: true
  # keep-ipynb: true
  # keep-md: true
  freeze: auto
# header-includes: |
#   <link rel="preconnect" href="https://fonts.googleapis.com">
#   <link href="https://iosevka-webfonts.github.io/iosevka/iosevka.css" rel="stylesheet">

#     <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
#     <script src="https://twemoji.maxcdn.com/v/latest/twemoji.min.js" crossorigin="anonymous"></script>
#     <script>
#         $(document).ready
#         (
#           function()
#           {
#                 twemoji.parse(document.body);
#           }
#         );
#     </script>
#
