title: "Sam Foreman"
date: last-modified
# date: today
author-title: ""
affiliation-title: ""
published-title: ""
modified-title: ""
title-block-categories: false
number-sections: false
bibliography: references.bib
# appendix-cite-as: display
favicon: "favicon.svg"
# twitter-card: true
site-url: https://samforeman.me
google-scholar: true
citeproc: true
project:
  render:
    - index.qmd
    - qmd/*.qmd
    - qmd/blog/*.qmd
  type: website
  output-dir: "docs"
  preview:
    port: 4209
author:
  # name: Sam Foreman
  name: "Sam Foreman [[{{< ai orcid >}}]{.orcid-green}](https://orcid.org/0000-0002-9981-0876)"
  url: https://samforeman.me
  # orcid: 0000-0002-9981-0876
  email: foremans@anl.gov
  # affiliation: Argonne National Laboratory
  # affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
citation:
   author: Sam Foreman
   type: webpage
   title: "Personal Website"
   url: https://samforeman.me
execute:
  keep-ipynb: true
  # keep-md: true
  freeze: auto
website:
  description: "My ramblings about science and computers"
  twitter-card:
    image: "./assets/thumbnail.png"
    site: "@saforem2"
    creator: "@saforem2"
  page-navigation: true
  title: "Sam Foreman"
  site-url: "https://samforeman.me"
  favicon: "./favicon.svg"
  back-to-top-navigation: true
  # reader-mode: true
  open-graph: true
  repo-url: https://github.com/saforem2/personal_site
  repo-actions: [source, edit, issue]
  google-analytics: G-XVM2Y822Y1
  sidebar: false
  navbar:
    logo: "./favicon.svg"
    background: "#222222"
    foregound: "#777777"
    left:
    # left:
      - href: "./qmd/posts.qmd"
        text: "[{{< bi signpost-split >}}]{.red-text} Posts"
      # - href: ""
      #   text: " "
      # - href: "./qmd/posts.qmd"
      #   text: "[{{< bi newspaper >}}]{.red-text} Posts"
      - href: "./qmd/slides.qmd"
        text: "[{{< bi easel >}}]{.green-text} Talks"
      - href: "./qmd/projects.qmd"
        text: "[{{< bi braces-asterisk >}}]{.blue-text} Projects"
    right:
      - icon: github
        href: https://github.com/saforem2/personal_site
        aria-label: GitHub
  page-footer:
    left: "[samforeman.me](https://samforeman.me)"
    right: "Copyright 2023, Sam Foreman" 
    center:
      - href: https://samforeman.me
        text: "{{< fa solid home >}}"
      - icon: github
        href: https://github.com/saforem2
      - icon: twitter
        href: https://twitter.com/saforem2
      - href: "mailto:///foremans@anl.gov"
        text: "{{< fa regular paper-plane >}}"
      - href: https://www.twitter.com/saforem2
        text: "{{< fa brands twitter >}}"
      - href: https://scholar.google.com/citations?user=vV_1zDwAAAAJ&hl=en
        text: "{{< ai google-scholar >}}"
      - href: https://orcid.org/0000-0002-9981-0876
        text: "{{< ai orcid >}}"
      - href: https://www.last.fm/user/saforem2
        text: "{{< fa brands lastfm >}}"
      - href: https://open.spotify.com/user/saforem2
        text: "{{< fa brands spotify >}}"
      - href: https://www.instagram.com/saforem2
        text: "{{< fa brands instagram >}}"
      - href: https://linkedin.com/in/saforem2
        text: "{{< fa brands linkedin >}}"
format:
  html:
    callout-appearance: simple
    code-link: true
    code-line-numbers: false
    toc: true
    self-contained: false
    toc-location: right
    grid:
      body-width: 1150px
    fig-responsive: true
    anchor-sections: true
    # highlight-style: atom-one
    code-overflow: scroll
    code-fold: false
    code-copy: true
    code-summary: " "
    code-tools:
      source: repo
      toggle: true
      caption: none
    html-math-method: katex
    css:
      - css/default.css
      - css/callouts.css
      - css/profile.css
    theme:
      dark:
        - css/common.scss
        - css/dark.scss
        - css/syntax-dark.scss
        - css/callout-cards.scss
      light:
        - css/common.scss
        - css/light.scss
        - css/syntax-light.scss
        - css/callout-cards.scss
    smooth-scroll: false
    citations-hover: true
    footnotes-hover: true
    header-includes: |
      <link href="https://pvinis.github.io/iosevka-webfont/3.4.1/iosevka.css" rel="stylesheet" />
